spring:
    datasource:
        url: "jdbc:h2:mem:aokidb;DB_CLOSE_ON_EXIT=true"
        driverClassName: "org.h2.Driver"
    h2:
        console:
            enabled: true
    messages:
        basename: "messages"
    jpa:
        hibernate:      
            ddl-auto: "create-drop"      
            # database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
            