spring:
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: admin
        password: password
    messages:
        basename: "messages"
    h2:
        console:
            enabled: true
    jpa:
        show-sql: true
        hibernate:            
            # database-platform: org.hibernate.dialect.H2Dialect
            ddl-auto: "create"

            